---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
 # - name: centos-7.2
    driver:
      network:
      - ["private_network", {ip: "192.168.33.7"}]
 

suites:
  - name: default
    run_list:
      - recipe[apache::package]
    attributes:

