---
driver:
  name: docker
  use_sudo: false
  network:
 # - ["private_network", {ip: "192.168.33.34"}]
 # forward:
 # - 80:8080
provisioner:
  name: chef_zero

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test_resource::directory_create]
    attributes:
